#ifndef PAYBIZH
#define PAYBIZH
#define PAYBIZ_RESPONSE_CODE_OK "GR001"
#define PAYBIZ_RESPONSE_CODE_FAILED "GR003"
#define PAYBIZ_RESPONSE_CODE_REFUND "GR018"
#define PAYBIZ_RESPONSE_CODE_PENDING "GR033"
#endif
